# Generated by Django 5.2.6 on 2025-10-14 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название симптома')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('points', models.IntegerField(verbose_name='Баллы по шкале Уэллса')),
                ('image_key', models.CharField(max_length=100, verbose_name='Ключ изображения в Minio')),
                ('image_ext', models.CharField(default='jpg', max_length=10, verbose_name='Расширение файла')),
                ('risk_factor', models.CharField(max_length=200, verbose_name='Фактор риска')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клинический симптом',
                'verbose_name_plural': 'Клинические симптомы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SymptomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория симптомов',
                'verbose_name_plural': 'Категории симптомов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершена'), ('deleted', 'Удалена')], db_index=True, default='draft', max_length=10, verbose_name='Статус')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Низкий риск'), ('moderate', 'Средний риск'), ('high', 'Высокий риск')], max_length=20, verbose_name='Уровень риска')),
                ('topic', models.CharField(default='Оценка риска ТГВ/ТЭЛА', max_length=180, verbose_name='Тема оценки')),
                ('recommendation', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Оценка риска',
                'verbose_name_plural': 'Оценки риска',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество/Выраженность')),
                ('symptom_points', models.IntegerField(help_text='Баллы на момент добавления', verbose_name='Баллы симптома')),
                ('note', models.CharField(blank=True, max_length=220, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptom_assessments', to='wells.clinicalsymptom', verbose_name='Симптом')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_symptoms', to='wells.riskassessment', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Симптом в оценке',
                'verbose_name_plural': 'Симптомы в оценке',
            },
        ),
        migrations.AddField(
            model_name='clinicalsymptom',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptoms', to='wells.symptomcategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['patient', 'status'], name='wells_riska_patient_a070fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsymptom',
            constraint=models.UniqueConstraint(fields=('assessment', 'symptom'), name='unique_assessment_symptom'),
        ),
    ]
