# Generated by Django 5.2.6 on 2025-10-14 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='formation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AlterField(
            model_name='assessmentsymptom',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_symptoms', to='wells.riskassessment', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Низкий риск'), ('moderate', 'Умеренный риск'), ('high', 'Высокий риск')], max_length=20, verbose_name='Уровень риска'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('formed', 'Сформирован'), ('completed', 'Завершен'), ('rejected', 'Отклонен'), ('deleted', 'Удален')], db_index=True, default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('patient',), name='unique_draft_risk_assessment_per_patient'),
        ),
    ]
