# Generated by Django 5.2.7 on 2025-10-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0003_remove_symptomcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsymptom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assessmentsymptom',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='clinicalsymptom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clinicalsymptom',
            name='image_ext',
        ),
        migrations.RemoveField(
            model_name='clinicalsymptom',
            name='image_key',
        ),
        migrations.RemoveField(
            model_name='clinicalsymptom',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clinicalsymptom',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='assessmentsymptom',
            name='note',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='assessmentsymptom',
            name='symptom_points',
            field=models.IntegerField(help_text='Баллы на момент добавления', null=True, verbose_name='Баллы симптома'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='recommendation',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Низкий риск'), ('moderate', 'Умеренный риск'), ('high', 'Высокий риск')], max_length=20, null=True, verbose_name='Уровень риска'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='topic',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Тема оценки'),
        ),
    ]
