# Generated by Django 5.2.7 on 2025-11-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_remove_assessmentsymptom_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsymptom',
            name='note',
        ),
        migrations.RemoveField(
            model_name='assessmentsymptom',
            name='quantity',
        ),
    ]
